Repository ie3-institute/PowerSystemUtils, pull requests merged in 2020-04, with the labels that each got.

#19 New TimeUtil
  Jenkinsfile
  src/main/java/edu/ie3/util/TimeTools.java
  src/main/java/edu/ie3/util/TimeUtil.java
  src/test/groovy/edu/ie3/util/TimeUtilsTest.groovy
Labels: bug, enhancement

#21 Introducing a QuantityUtil that is able to make Quantities comparable
  src/main/java/edu/ie3/util/quantities/QuantityUtil.java
  src/test/groovy/edu/ie3/util/quantities/QuantityUtilTest.groovy
Labels: enhancement, good first issue

#22 Let the beast (TimeUtil) out of its cage
  src/main/java/edu/ie3/util/TimeUtil.java
Labels: bug

#24 Consolidate and enhance GeoUtils
  build.gradle
  src/main/java/edu/ie3/util/StringUtils.java
  src/main/java/edu/ie3/util/geo/GeoUtils.java
  src/test/groovy/edu/ie3/util/StringUtilsTest.groovy
  src/test/groovy/edu/ie3/util/geo/GeoUtilsTest.groovy
Labels: enhancement, good first issue

#25 extended StringUtils
  src/main/java/edu/ie3/util/StringUtils.java
  src/test/groovy/edu/ie3/util/StringUtilsTest.groovy
Labels: enhancement

#26 Open default constructor to children
  src/main/java/edu/ie3/util/geo/GeoUtils.java
Labels: bug
