Repository ie3-institute/PowerSystemUtils, pull requests merged in 2021-04, with the labels that each got.

#80 Set dependency version to fixed version
  CHANGELOG.md
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: bug

#87 Test for CoordinateDistance
  src/main/java/edu/ie3/util/geo/CoordinateDistance.java
  src/test/groovy/edu/ie3/util/geo/CoordinateDistanceTest.groovy
Labels: bug

#84 prepare for v1.5 release
  CHANGELOG.md
  build.gradle
  src/main/java/edu/ie3/util/StreamUtils.java
  src/main/java/edu/ie3/util/StringUtils.java
  src/main/java/edu/ie3/util/copy/DeepCopy.java
  src/main/java/edu/ie3/util/geo/GeoUtils.java
Labels: release

#89 Fix malicious implementation of units
  CHANGELOG.md
  build.gradle
  src/main/java/edu/ie3/util/quantities/PowerSystemUnits.java
  src/test/groovy/edu/ie3/util/quantities/PowerSystemUnitsTest.groovy
Labels: bug

#90 set version back to 1.6-SNAPSHOT
  build.gradle
Labels: release

#92 Add a class that aids in providing namings in different naming conventions
  CHANGELOG.md
  build.gradle
  src/main/java/edu/ie3/util/StringUtils.java
  src/main/java/edu/ie3/util/naming/Naming.java
  src/main/java/edu/ie3/util/naming/NamingConvention.java
  src/test/groovy/edu/ie3/util/StringUtilsTest.groovy
  src/test/groovy/edu/ie3/util/naming/NamingTest.groovy
Labels: enhancement

#93 back to snap shot
  build.gradle
Labels: release
