Repository ie3-institute/PowerSystemUtils, pull requests merged in 2022-01, with the labels that each got.

#197 Release v1.6.0
  CHANGELOG.md
  build.gradle
  src/main/java/edu/ie3/util/OneToOneMap.java
  src/main/java/edu/ie3/util/io/xmladapter/StringToIntegerListAdapter.java
  src/main/java/edu/ie3/util/io/xmladapter/StringToStringListAdapter.java
  src/main/java/edu/ie3/util/io/xmladapter/YearAdapter.java
Labels: release

#207 Fix tests in CI
  CHANGELOG.md
  build.gradle
  gradle/scripts/sonarqube.gradle
  gradle/scripts/spotless.gradle
  gradle/scripts/test.gradle
  src/main/java/edu/ie3/util/quantities/EmptyQuantity.java
  src/test/groovy/edu/ie3/util/io/FileIOUtilsTest.groovy
  src/test/groovy/edu/ie3/util/quantities/EmptyQuantityTest.groovy
Labels: bug

#205 Increase code quality
  CHANGELOG.md
  gradle/scripts/jacoco.gradle
  gradle/scripts/sonarqube.gradle
  src/main/java/edu/ie3/util/EmpiricalRandom.java
  src/main/java/edu/ie3/util/geo/GeoUtils.java
  src/main/java/edu/ie3/util/io/FileIOUtils.java
  src/main/java/edu/ie3/util/quantities/EmptyQuantity.java
  src/main/java/edu/ie3/util/quantities/QuantityUtil.java
  src/main/java/edu/ie3/util/quantities/interfaces/EnergyDensity.java
  src/main/java/edu/ie3/util/quantities/interfaces/PowerDensity.java
  src/test/groovy/edu/ie3/util/geo/GeoUtilsTest.groovy
Labels: bug

#175 To/#163 adapt geo utils
  CHANGELOG.md
  src/main/java/edu/ie3/util/geo/CoordinateDistance.java
  src/main/java/edu/ie3/util/geo/GeoUtils.java
  src/main/scala/edu/ie3/util/exceptions/GeoException.scala
  src/main/scala/edu/ie3/util/exceptions/OsmException.scala
  src/main/scala/edu/ie3/util/geo/CoordinateDistance.scala
  src/main/scala/edu/ie3/util/geo/GeoUtils.scala
  src/main/scala/edu/ie3/util/geo/RichGeometries.scala
  src/main/scala/edu/ie3/util/osm/OsmEntities.scala
  src/main/scala/edu/ie3/util/osm/OsmUtils.scala
  src/main/scala/edu/ie3/util/quantities/QuantityUtils.scala
  src/test/groovy/edu/ie3/util/geo/CoordinateDistanceTest.groovy
  src/test/groovy/edu/ie3/util/geo/GeoUtilsTest.groovy
  src/test/scala/edu/ie3/util/geo/GeoUtilsSpec.scala
  src/test/scala/edu/ie3/util/geo/RichGeometriesSpec.scala
Labels: enhancement

#209 Adjust jacoco coverage criterion
  gradle/scripts/jacoco.gradle
  gradle/scripts/sonarqube.gradle
Labels: enhancement

#211 Fix (most severe) JavaDoc issues
  src/main/java/edu/ie3/util/copy/FastByteArrayOutputStream.java
  src/main/java/edu/ie3/util/geo/GrahamScan.java
Labels: bug

#216 Fix deployment
  Jenkinsfile
Labels: bug

#193 Improved OSM model
  CHANGELOG.md
  Jenkinsfile
  build.gradle
  gradle/scripts/checkJavaVersion.gradle
  gradle/scripts/jacoco.gradle
  gradle/scripts/test.gradle
  src/main/scala/edu/ie3/util/geo/RichGeometries.scala
  src/main/scala/edu/ie3/util/osm/OsmContainerUtils.scala
  src/main/scala/edu/ie3/util/osm/OsmEntities.scala
  src/main/scala/edu/ie3/util/osm/OsmModel.scala
  src/main/scala/edu/ie3/util/osm/OsmUtils.scala
  src/main/scala/edu/ie3/util/osm/model/CommonOsmKey.scala
  src/main/scala/edu/ie3/util/osm/model/OsmContainer.scala
  src/main/scala/edu/ie3/util/osm/model/OsmEntity.scala
  src/main/scala/edu/ie3/util/osm/model/RelationEntitiesSupport.scala
  src/main/scala/edu/ie3/util/osm/model/RichClosedWaySupport.scala
  src/main/scala/edu/ie3/util/osm/model/WayCache.scala
  src/test/groovy/edu/ie3/util/io/FileIOUtilsTest.groovy
  src/test/scala/edu/ie3/util/osm/OsmContainerUtilsSpec.scala
  src/test/scala/edu/ie3/util/osm/OsmEntitiesSpec.scala
  src/test/scala/edu/ie3/util/osm/OsmUtilsSpec.scala
  src/test/scala/edu/ie3/util/osm/SimpleOsmTestData.scala
  src/test/scala/edu/ie3/util/osm/model/OsmContainerSpec.scala
  src/test/scala/edu/ie3/util/osm/model/OsmEntitySpec.scala
Labels: enhancement, invalid
