Repository ie3-institute/PowerSystemUtils, pull requests merged in 2024-02, with the labels that each got.

#438 Update gradle to 8.6
  CHANGELOG.md
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: dependencies

#440 Release 2.1
  CHANGELOG.md
  build.gradle
Labels: release

#443 Remove unused fields from TimeUtil
  src/main/java/edu/ie3/util/TimeUtil.java
  src/test/groovy/edu/ie3/util/TimeUtilTest.groovy
Labels: enhancement
