Repository ie3-institute/PowerSystemUtils, pull requests merged in 2025-04, with the labels that each got.

#545 Integrated semVer Gradle plugin to project
  CHANGELOG.md
  build.gradle
  gradle/scripts/semVer.gradle
  version.properties
Labels: enhancement, dependencies

#541 Implementation of GitHub Actions
  .github/workflows/ci.yml
  .github/workflows/dependabot-auto-merge.yml
  CHANGELOG.md
  build.gradle
  gradle/scripts/branchName.gradle
  scripts/branch_type.sh
  scripts/get_versions.sh
  scripts/run-version-check.sh
  scripts/version_check.sh
Labels: ci

#547 Deleted Jenkinsfile and fixed Deployment
  CHANGELOG.md
  Jenkinsfile
  build.gradle
  gradle/scripts/mavenCentralPublish.gradle
Labels: ci

#550 Fixing missing sources in releases.
  CHANGELOG.md
  gradle/scripts/mavenCentralPublish.gradle
Labels: bug

#558 Fixed Version-Check
  CHANGELOG.md
  scripts/version_check.sh
Labels: bug

#560 Fixed the fix of version Check
  .github/workflows/dependabot-auto-merge.yml
  .github/workflows/dependabot-review.yml
  CHANGELOG.md
  scripts/version_check.sh
Labels: bug, ci
